-- GENERATED by scripts/build-seed-sql.ts from seed/series/en-la-casa-de-dona-poliza.json — do not edit by hand.

-- Idempotent: re-running never duplicates or overwrites rows.

insert into public.vs_series (slug, name, language, target_audience, visual_style, bible)
values ('en-la-casa-de-dona-poliza', 'En la casa de Doña Póliza', 'es', 'Adultos hispanohablantes que se preparan para el examen de licencia de seguros de vida de Florida (2-14).', 'Colorful 3D animated series, warm Caribbean/Florida neighborhood palette, soft sunlight, expressive family-friendly character animation, 16:9.', '{"generation_rules":["Educational facts come only from verified Content Locks; never invent or change numbers.","Dialogue is spoken exactly as written in the approved script.","No on-screen text, captions, logos or signs generated by the video model.","Doña Póliza explains concepts with pastries whenever possible."],"continuity_rules":["Characters keep the same face, age, body type and wardrobe in every clip.","Doña Póliza always wears her apron and glasses near the tip of her nose.","La Voz del Examen is never shown on screen."],"negative_prompt":"on-screen text, subtitles, watermark, logo, extra characters, photorealistic, horror, distorted faces","defaults":{"provider":"mock","model":"mock-video-1","resolution":"2K","ratio":"16:9"},"content_lock_scopes":["FL-2-14"],"default_location_slug":"casa-de-dona-poliza"}'::jsonb)
on conflict (slug) do nothing;

insert into public.vs_characters (series_id, slug, name, aliases, age, description, personality, wardrobe, visual_prompt, negative_prompt, continuity_notes, rules, voice_only, voice)
values ((select id from public.vs_series where slug = 'en-la-casa-de-dona-poliza'), 'dona-poliza', 'Doña Póliza', array['Dona Poliza', 'DOÑA PÓLIZA', 'Doña']::text[], 68, 'Puerto Rican grandmother in a Florida neighborhood. Thirty years selling life insurance in Florida. Also sells pastries from her home.', array['funny', 'warm', 'confident', 'direct', 'neighborhood grandmother energy', 'very knowledgeable']::text[], 'Apron over a colorful house dress; glasses resting near the tip of her nose; carries a wooden spoon she uses for pointing.', '68-year-old Puerto Rican grandmother, warm expressive face, apron, glasses near the tip of her nose, wooden spoon in hand for pointing.', 'younger woman, no apron, no glasses, different hairstyle', 'Apron, glasses and wooden spoon are her visual identifiers and must always be present.', array['If you cannot explain it with a pastry, you do not understand it.', 'She never intentionally uses English insurance terminology; if an English term slips out she corrects herself (recurring joke).']::text[], false, '{"provider":"minimax-native","description":"Warm, confident Puerto Rican Spanish, older woman, playful and direct."}'::jsonb)
on conflict (series_id, slug) do nothing;

insert into public.vs_characters (series_id, slug, name, aliases, age, description, personality, wardrobe, visual_prompt, negative_prompt, continuity_notes, rules, voice_only, voice)
values ((select id from public.vs_series where slug = 'en-la-casa-de-dona-poliza'), 'el-sobrino', 'El Sobrino', array['Sobrino', 'EL SOBRINO']::text[], 9, 'Funny, observant 9-year-old nephew. Usually appears briefly, says an uncomfortable or obvious truth and leaves. Gets the final line or punchline when appropriate.', array['funny', 'observant', 'blunt']::text[], '', '9-year-old boy, curious expression, casual clothes.', 'older child, teenager', 'Brief appearances; enters, delivers a line, exits.', array['Gets the final line or punchline of episodes when appropriate.']::text[], false, '{"provider":"minimax-native","description":"9-year-old boy, Spanish, deadpan and matter-of-fact."}'::jsonb)
on conflict (series_id, slug) do nothing;

insert into public.vs_characters (series_id, slug, name, aliases, age, description, personality, wardrobe, visual_prompt, negative_prompt, continuity_notes, rules, voice_only, voice)
values ((select id from public.vs_series where slug = 'en-la-casa-de-dona-poliza'), 'la-voz-del-examen', 'La Voz del Examen', array['Voz del Examen', 'LA VOZ DEL EXAMEN', 'La Voz', 'VOZ']::text[], null, 'Voice only. Deep, overly dramatic voice that reads exam-style statements and questions. Doña Póliza frequently interrupts it or tells it to be quiet.', array['deep', 'overly dramatic']::text[], '', '', '', 'Never visible. Off-screen narrator voice.', array['Voice only; never appears on screen.']::text[], true, '{"provider":"minimax-native","description":"Deep, booming, overly dramatic announcer voice in Spanish."}'::jsonb)
on conflict (series_id, slug) do nothing;

insert into public.vs_assets (series_id, kind, slug, name, aliases, description, visual_prompt)
values ((select id from public.vs_series where slug = 'en-la-casa-de-dona-poliza'), 'location', 'casa-de-dona-poliza', 'Casa de Doña Póliza', array['casa', 'porch', 'portal', 'balcón', 'exterior', 'casa de doña póliza']::text[], 'Colorful Florida/Caribbean neighborhood home with a front porch and an outdoor pastry table. Warm atmosphere.', 'Colorful Florida-Caribbean neighborhood house, front porch, outdoor table with pastry trays, warm afternoon light.')
on conflict (series_id, slug) do nothing;

insert into public.vs_assets (series_id, kind, slug, name, aliases, description, visual_prompt)
values ((select id from public.vs_series where slug = 'en-la-casa-de-dona-poliza'), 'prop', 'cuchara-de-madera', 'Wooden spoon', array['cuchara', 'wooden spoon']::text[], 'Doña Póliza''s pointing spoon.', '')
on conflict (series_id, slug) do nothing;

insert into public.vs_assets (series_id, kind, slug, name, aliases, description, visual_prompt)
values ((select id from public.vs_series where slug = 'en-la-casa-de-dona-poliza'), 'prop', 'bandejas-de-pastelillos', 'Pastry trays', array['bandeja', 'bandejas']::text[], 'Trays of pastries.', '')
on conflict (series_id, slug) do nothing;

insert into public.vs_assets (series_id, kind, slug, name, aliases, description, visual_prompt)
values ((select id from public.vs_series where slug = 'en-la-casa-de-dona-poliza'), 'prop', 'pastelillos', 'Pastries', array['pastelillo', 'pastelillos', 'pastries', 'quesitos']::text[], 'Puerto Rican pastries.', '')
on conflict (series_id, slug) do nothing;

insert into public.vs_assets (series_id, kind, slug, name, aliases, description, visual_prompt)
values ((select id from public.vs_series where slug = 'en-la-casa-de-dona-poliza'), 'prop', 'delantal', 'Apron', array['delantal', 'apron']::text[], 'Doña Póliza''s apron.', '')
on conflict (series_id, slug) do nothing;

insert into public.vs_assets (series_id, kind, slug, name, aliases, description, visual_prompt)
values ((select id from public.vs_series where slug = 'en-la-casa-de-dona-poliza'), 'prop', 'mesa', 'Table', array['mesa', 'table']::text[], 'Outdoor pastry table on the porch.', '')
on conflict (series_id, slug) do nothing;

insert into public.vs_assets (series_id, kind, slug, name, aliases, description, visual_prompt)
values ((select id from public.vs_series where slug = 'en-la-casa-de-dona-poliza'), 'prop', 'libreta', 'Notebook', array['libreta', 'cuaderno', 'notebook']::text[], 'Notebook.', '')
on conflict (series_id, slug) do nothing;
