// Generates supabase/seed/10_series_*.sql from seed/series/*.json so the
// series bible has ONE source (the JSON), used by both the database seed and
// the in-memory demo. Run: npm run seed:sql
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

function lit(v: unknown): string {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  return `'${String(v).replaceAll("'", "''")}'`;
}
const arr = (xs: string[] = []) => `array[${xs.map(lit).join(', ')}]::text[]`;
const json = (o: unknown) => `${lit(JSON.stringify(o ?? {}))}::jsonb`;

export function buildSeedSql(bible: any): string {
  const s = bible.series;
  const out: string[] = [];
  out.push(`-- GENERATED by scripts/build-seed-sql.ts from seed/series/${s.slug}.json — do not edit by hand.`);
  out.push('-- Idempotent: re-running never duplicates or overwrites rows.');
  out.push(
    `insert into public.vs_series (slug, name, language, target_audience, visual_style, bible)\n` +
      `values (${lit(s.slug)}, ${lit(s.name)}, ${lit(s.language)}, ${lit(s.target_audience)}, ${lit(s.visual_style)}, ${json(s.bible)})\n` +
      `on conflict (slug) do nothing;`,
  );
  const sid = `(select id from public.vs_series where slug = ${lit(s.slug)})`;
  for (const c of bible.characters) {
    out.push(
      `insert into public.vs_characters (series_id, slug, name, aliases, age, description, personality, wardrobe, visual_prompt, negative_prompt, continuity_notes, rules, voice_only, voice)\n` +
        `values (${sid}, ${lit(c.slug)}, ${lit(c.name)}, ${arr(c.aliases)}, ${lit(c.age)}, ${lit(c.description)}, ${arr(c.personality)}, ${lit(c.wardrobe)}, ${lit(c.visual_prompt)}, ${lit(c.negative_prompt)}, ${lit(c.continuity_notes)}, ${arr(c.rules)}, ${lit(c.voice_only)}, ${json(c.voice)})\n` +
        `on conflict (series_id, slug) do nothing;`,
    );
  }
  for (const a of bible.assets) {
    out.push(
      `insert into public.vs_assets (series_id, kind, slug, name, aliases, description, visual_prompt)\n` +
        `values (${sid}, ${lit(a.kind)}, ${lit(a.slug)}, ${lit(a.name)}, ${arr(a.aliases)}, ${lit(a.description ?? '')}, ${lit(a.visual_prompt ?? '')})\n` +
        `on conflict (series_id, slug) do nothing;`,
    );
  }
  return out.join('\n\n') + '\n';
}

export function seedTargets(): { json: string; sql: string }[] {
  const dir = join(ROOT, 'seed', 'series');
  return readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => ({ json: join(dir, f), sql: join(ROOT, 'supabase', 'seed', `10_series_${f.replace(/\.json$/, '')}.sql`) }));
}

if (import.meta.url === `file://${process.argv[1]}`) {
  for (const t of seedTargets()) {
    writeFileSync(t.sql, buildSeedSql(JSON.parse(readFileSync(t.json, 'utf8'))));
    console.log('wrote', t.sql);
  }
}
